name: SSH Deployment 2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ vars.SSHKEY }}

      - name: Git Pull
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan -t rsa ${{ vars.HOST }} >> ~/.ssh/known_hosts
          ssh ${{ vars.USERNAME }}@${{ vars.HOST }} "cd ${{ home/projeto3 }} && git pull origin main"
          echo "Successfully pulled repo."

      - name: Check Nginx configuration
        run: |
          echo "Checking nginx config"
          ssh ${{ vars.SSHKEY }}@${{ vars.HOST }} "sudo /usr/sbin/nginx -t 2>&1"
          echo "Nginx configuration check completed."

      - name: Restart Nginx service
        if: success()
        run: |
          ssh ${{ vars.USERNAME }}@${{ vars.HOST }} "sudo /bin/systemctl restart nginx"
          echo "Nginx service restarted successfully"        
