name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/scp-action@v0.1.4

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master 
      with:
        HOST: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        source: "."
        target: "/var/www/mywebsite"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        #PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        script: ls
