name: Checkout

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files check
        uses: actions/checkout@v4
        id: changed-files
      - name: Get changed files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          separator: ","
        
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key:  ${{ vars.SSHKEY }}
          password: ${{ vars.PSW }}
          port: ${{ vars.PORT }}
          source: "./*"
          target: /irineu/



