name: Deployed

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        #PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        script: ls
