name: Upa File 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure stuff
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        script: |
          export TERM=xterm
    
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: arquivos
        remote: home/projeto
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        password: ${{ vars.PSW }}
