env:
  BUILD_NAME: "${{ github.RUN_ID }}_${{ github.RUN_NUMBER }}"
  BUILD_NAME_EXT: "${{ github.RUN_ID }}_${{ github.RUN_NUMBER }}.tar.gz"
  
name: Deployed

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ vars.HOST }}
          USERNAME: ${{ vars.USERNAME }}
          PORT: ${{ vars.PORT }}
          KEY: ${{ vars.SSHKEY }}
          source: "."
          target: "~/home/www.docker.digitalmegaofertas.com/src/"
          overwrite: true
          timeout: 1m

