name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "baixar o código"
        uses: actions@checkout@v4

      - name: "copy file via ssh password"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "82.112.245.91"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/sistema"

  
