name: Upa File 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy folder content recursively to remote
      uses: actions/checkout@v4
      with:
        local: .
        remote: home/projeto2/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        privateKey: ${{ secrets.PRIVATE_KEY}}
