name: "Deploy para VPS 6"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Construindo o APP"

#deploy desenvolvimento
  deploy-development:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{vars.TARGET}}
    #needs: deploy-development
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{vars.REMOTE_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          TARGET: ${{vars.TARGET}}




  
