name: Upa File 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure stuff
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        script: |
          export TERM=xterm

    
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ vars.HOST }}
        USERNAME: ${{ vars.USERNAME }}
        PORT: ${{ vars.PORT }}
        KEY: ${{ vars.SSHKEY }}
        passphrase: ${{secrets.PSW}}
        source: "."
        target: "~/home/teste4/"
        strip_components: 2
