name: Upa File 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        password: ${{ vars.PSW }}
        port: 22
        source: "arquivos/foiBitch.txt"
        target: home/projeto2
