name: Copy File Workflow 23

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /chora/hello.txt
          remote: srv611531.hstgr.cloud
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PSWD }}
