name: Deploy 2 🚀
on:
    push:
    branches:
        - master
jobs:
    deploy:
    runs-on: ubuntu-latest
    steps:
        - name: SSH Deploy
        run: |
            sshpass -p ${{ secrets.PSWD }} ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.USER}}@${{ secrets.VPS_IP }} 'cd ~/home/srv611531.hstgr.cloud'
        env:
            SSHPASS: ${{ secrets.PSWD }}
