name: Copy File Workflow

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: chora/hello.txt
          remote: scp/single/oof.txt
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PSWD }}
